### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by okeshka** [okeshka/homepage_2021#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by okeshka-kpi** [comment]
Байден, который более 35 лет был сенатором от штата Делавэр и занимал пост вице-президента в администрации 44-го главы американского государства Барака Обамы, считается одним из самых авторитетных и опытных представителей Демпартии. На момент инаугурации 20 января 2021 года ему будет 78 лет: таким образом, он станет самым пожилым президентом за всю историю США.
