### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by okeshka** [okeshka/homepage_2021#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by okeshka-kpi** [comment]
https://www.facebook.com/joebiden
https://twitter.com/JoeBiden
https://instagram.com/joebiden
