### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by okeshka** [okeshka/homepage_2021#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме

**Comment by okeshka-kpi** [comment]
Начало политической карьеры (1970—1972)  В 1970 году Байден был избран членом Совета округа Ньюкасл[en] от 4-го округа. Его предшественник, республиканец Генри Р. Фолсом предпочёл баллотироваться в члены совета от 5-го округа. 5 января 1971 года Байден принёс присягу. В совете он запомнился как убеждённый противник строительства высокоскоростных магистралей на территории своего округа.  1 января 1973 года Байден подал в отставку из окружного совета в связи с избранием в Сенат США. Его преемником совете стал демократ Фрэнсис Р. Свифт.
В 1972 году Джо Байден был впервые избран в Сенат США от штата Делавэр, одержав неожиданную победу над действующим сенатором и бывшим губернатором штата Калебом Боггсом. На момент избрания ему было 29 лет, минимального для сенаторов 30-летнего возраста он достиг незадолго до инаугурации. Переизбирался в 1978, 1984, 1990, 1996, 2002 и 2008 годах. 
После того, как кандидатом от демократов стал Барак Обама, он 23 августа 2008 года выбрал Джо Байдена в качестве кандидата на пост вице-президента.
20 января 2021 года в 11:49 по Североамериканскому восточному времени Джо Байден произнёс присягу на Библии и вступил в должность 46-го главы государства. В рамках 59-й по счёту церемонии инаугурации Байден на западном крыльце Капитолия произнёс текст присяги, состоящий из 35 слов, на Библии.
