### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by okeshka** [okeshka/homepage_2021#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by okeshka-kpi** [comment]
За первые два дня на посту президента Байден подписал 17 указов — больше, чем большинство последних президентов за первые 100 дней. К третьему дню своего президентства Джо Байден отменил ряд указов Дональда Трампа: остановил выход из ВОЗ и Парижского соглашения по климату, строительство стены на границе с Мексикой, разрешил гражданам из ряда мусульманских и африканских стран въезд в США и отменил строительство нефтепровода Keystone XL по просьбе экологов, также новоизбранный президент обязал носить медицинские маски в госучреждениях и при пересечении штатов.
Байден не употребляет алкоголь, так как, по его словам, «В моей семье было достаточно алкоголиков»
